# config/fourth_dimension_database.yml
default: &default
  encoding: utf8
  adapter: mysql2
  port: 5500

development:
  <<: *default
  database: ClientDB_development
  host:
  username: root
  password: password

test:
  <<: *default
  host: localhost
  username: root
  password: password
  database: ClientDB_test